const { admin, db, auth } = require('../config/firebase');

// @desc    Register a new user
// @route   POST /api/auth/register
// @access  Public
const registerUser = async (req, res) => {
  try {
    const { email, password, firstName, lastName } = req.body;

    if (!email || !password || !firstName || !lastName) {
      return res.status(400).json({ message: 'All fields are required' });
    }

    // 1. Create User in Firebase Authentication
    const userRecord = await auth.createUser({
      email,
      password,
      displayName: `${firstName} ${lastName}`,
    });

    // 2. Store additional user info in Firestore
    const userDoc = {
      email,
      firstName,
      lastName,
      role: 'user', // default role
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
      uid: userRecord.uid
    };

    await db.collection('users').doc(userRecord.uid).set(userDoc);

    // 3. (Optional for Option A) Create a Custom JWT for your backend,
    //    or just return the minimal user object and have the frontend handle session.
    // Since Firebase doesn't natively return an ID Token on createUser (it only does on the client SDK),
    // we can create a custom token to send to the client.
    const customToken = await auth.createCustomToken(userRecord.uid, { role: 'user' });

    res.status(201).json({
      message: 'User registered successfully',
      user: {
        id: userRecord.uid,
        email,
        firstName,
        lastName,
        role: 'user'
      },
      token: customToken
    });

  } catch (error) {
    console.error('Registration Error:', error);
    // Handle specific Firebase errors (e.g., email already exists)
    if (error.code === 'auth/email-already-exists') {
      return res.status(400).json({ message: 'Email is already in use' });
    }
    if (error.code === 'auth/invalid-password') {
      return res.status(400).json({ message: 'Password must be at least 6 characters' });
    }
    
    res.status(500).json({ message: 'Server Error during registration' });
  }
};

// @desc    Login user
// @route   POST /api/auth/login
// @access  Public
const loginUser = async (req, res) => {
  try {
    const { email, password } = req.body;

    if (!email || !password) {
      return res.status(400).json({ message: 'Please provide email and password' });
    }

    // In Option A (Full Backend Control), verifying a password using only the Firebase Admin SDK 
    // is tricky because Firebase Admin doesn't have a "signInWithEmailAndPassword" method.
    // The intended architecture for Firebase is almost always to let the Client SDK verify the password.
    
    // WORKAROUND for Option A: Use the Firebase REST Auth API to verify the password.
    // We need the Web API Key for this.
    
    const apiKey = process.env.FIREBASE_WEB_API_KEY;
    if (!apiKey) {
      return res.status(500).json({ message: 'Server configuration error (missing Web API Key)' });
    }

    const authResponse = await fetch(`https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=${apiKey}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ email, password, returnSecureToken: true })
    });

    const authData = await authResponse.json();

    if (!authResponse.ok) {
      console.error('Firebase Auth Error Details:', JSON.stringify(authData, null, 2));
      return res.status(400).json({ message: 'Invalid credentials' });
    }

    // Fetch user details from Firestore
    const userDoc = await db.collection('users').doc(authData.localId).get();
    
    if (!userDoc.exists) {
       return res.status(404).json({ message: 'User profile not found in database' });
    }

    const userData = userDoc.data();

    // In this flow, we can just return the ID token generated by the REST API,
    // which the frontend can use as a Bearer token in subsequent requests.
    res.json({
      message: 'Logged in successfully',
      user: {
        id: authData.localId,
        email: userData.email,
        firstName: userData.firstName,
        lastName: userData.lastName,
        role: userData.role
      },
      token: authData.idToken
    });

  } catch (error) {
    console.error('Login Error:', error);
    res.status(500).json({ message: 'Server Error during login' });
  }
};

// @desc    Send Password Reset Email
// @route   POST /api/auth/forgot-password
// @access  Public
const forgotPassword = async (req, res) => {
  try {
    const { email } = req.body;
    if (!email) return res.status(400).json({ message: 'Email is required' });

    const apiKey = process.env.FIREBASE_WEB_API_KEY;
    if (!apiKey) {
      return res.status(500).json({ message: 'Server configuration error' });
    }

    const authResponse = await fetch(`https://identitytoolkit.googleapis.com/v1/accounts:sendOobCode?key=${apiKey}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ requestType: "PASSWORD_RESET", email })
    });

    const authData = await authResponse.json();
    if (!authResponse.ok) {
       return res.status(400).json({ message: authData.error?.message || 'Failed to send reset email' });
    }

    res.json({ message: 'Password reset email sent' });
  } catch (error) {
    console.error('Forgot Password Error:', error);
    res.status(500).json({ message: 'Server Error' });
  }
};

// @desc    Login via Google
// @route   POST /api/auth/google
// @access  Public
const googleLogin = async (req, res) => {
  try {
    const { token } = req.body;
    if (!token) return res.status(400).json({ message: 'No token provided' });

    // Verify token using Firebase Admin
    const decodedToken = await admin.auth().verifyIdToken(token);
    const { uid, email, name } = decodedToken;
    
    let userDoc = await db.collection('users').doc(uid).get();
    
    if (!userDoc.exists) {
      // Split display name into first and last
      const nameParts = name ? name.split(' ') : ['Google', 'User'];
      const firstName = nameParts[0];
      const lastName = nameParts.slice(1).join(' ');

      const newUser = {
        email,
        firstName,
        lastName,
        role: 'user',
        createdAt: admin.firestore.FieldValue.serverTimestamp(),
        uid
      };
      await db.collection('users').doc(uid).set(newUser);
      userDoc = await db.collection('users').doc(uid).get();
    }

    const userData = userDoc.data();

    res.json({
      message: 'Google login successful',
      user: {
        id: uid,
        email: userData.email,
        firstName: userData.firstName,
        lastName: userData.lastName,
        role: userData.role
      },
      token
    });
  } catch (error) {
    console.error('Google Login Error:', error);
    res.status(500).json({ message: 'Server Error during Google authentication' });
  }
};

module.exports = {
  registerUser,
  loginUser,
  forgotPassword,
  googleLogin
};
